//package com.damai.test;
//
//import org.springframework.data.redis.connection.stream.MapRecord;
//import org.springframework.data.redis.connection.stream.RecordId;
//import org.springframework.data.redis.connection.stream.StreamRecords;
//import org.springframework.data.redis.core.RedisTemplate;
//
//import java.util.HashMap;
//
//public class TestStream {
//    
//    public void testStream(Long programId){
//        HashMap<String, Object> map = new HashMap<>();
//        map.put("id", String.valueOf(programId));
//        MapRecord<String, String, Object> record = StreamRecords.newRecord()
//                .in(StreamConstant.streamName)
//                .ofMap(map)
//                .withId(RecordId.autoGenerate());
//        RedisTemplate<String,String> instance = redisCache.getInstance();
//        RecordId recordId = instance.opsForStream().add(record);
//        // 是否是自动生成的
//        assert recordId != null;
//        boolean autoGenerated = recordId.shouldBeAutoGenerated();
//        // id值
//        String value = recordId.getValue();
//        // 序列号部分
//        Long sequence = recordId.getSequence();
//        // 时间戳部分
//        Long timestamp = recordId.getTimestamp();
//
//    }
//}
